version: '3'

services:
  node:
    build: ./node
    volumes:
      - ./node:/usr/src/app
    ports:
      - "8000:8124"

  express:
    build: ./express
    volumes:
      - ./express:/usr/src/app
    ports:
      - "1234:1234"


